import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'


// Components
import Header from "@/app/componentes/Header";


const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})


const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono',
  
  /*
  variable: '--font-body',
  */
})


export const metadata = {
  title: "Disco",  // Titulo de la Página
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn('antialiased', fontHeading.variable, fontBody.variable)} >
        <Header />
        {children}
        
      </body>
    </html>
  );
}
